import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "bin"))

from aikito_subagent import (  # noqa: E402
    SubagentConfigError,
    build_plan,
    has_aikito_marker,
    render_claude_markdown,
    render_codex_toml,
    render_copilot_markdown,
    sync_subagent_configs,
)


class SubagentSyncTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.base_path = Path(self.temp_dir.name)
        self.aikito_dir = self.base_path / "aikito"
        self.home_dir = self.base_path / "home"

        self.aikito_dir.mkdir()
        self.home_dir.mkdir()
        (self.aikito_dir / "subagents").mkdir()

        # Base agents.toml
        agents_toml = """
[agents.codex]
display_name = "Codex"
instruction_path = ".codex/AGENTS.md"

[agents.codex.subagents]
config_path = ".codex/agents"
config_format = "codex_toml"

[agents.claude-code]
display_name = "Claude Code"
instruction_path = ".claude/CLAUDE.md"
skills_path = ".claude/skills"

[agents.claude-code.subagents]
config_path = ".claude/agents"
config_format = "claude_markdown"

[agents.agy]
display_name = "Antigravity CLI (agy)"
instruction_path = ".gemini/GEMINI.md"

[agents.agy.subagents]
config_path = ".gemini/config/agents"
config_format = "agy_markdown"

[agents.opencode]
display_name = "OpenCode"
instruction_path = ".config/opencode/AGENTS.md"
"""
        (self.aikito_dir / "agents.toml").write_text(
            agents_toml.strip(), encoding="utf-8"
        )

        # Base subagents.toml
        subagents_toml = """
[subagents.formatter]
description = "Runs project-approved formatting and lint-fix operations."
agents = ["codex", "claude-code", "agy"]

[subagents.formatter.codex]
model = "gpt-5.4-mini"
model_reasoning_effort = "low"

[subagents.formatter.claude-code]
model = "haiku"
effort = "low"

[subagents.formatter.agy]
tools = ["run_command"]
"""
        (self.aikito_dir / "subagents.toml").write_text(
            subagents_toml.strip(), encoding="utf-8"
        )

        # Base instructions file
        instructions = """# Formatter

Perform only the assigned formatting or lint-fix task.
"""
        (self.aikito_dir / "subagents" / "formatter.md").write_text(
            instructions.strip(), encoding="utf-8"
        )

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def test_rendering_deterministic_and_correct(self) -> None:
        rendered_claude_1 = render_claude_markdown(
            "formatter",
            "Runs project-approved formatting and lint-fix operations.",
            {"model": "haiku", "effort": "low"},
            "# Formatter\n\nPerform only task.",
        )
        rendered_claude_2 = render_claude_markdown(
            "formatter",
            "Runs project-approved formatting and lint-fix operations.",
            {"effort": "low", "model": "haiku"},
            "# Formatter\n\nPerform only task.",
        )
        self.assertEqual(rendered_claude_1, rendered_claude_2)
        self.assertIn('name: "formatter"', rendered_claude_1)
        self.assertIn('effort: "low"', rendered_claude_1)
        self.assertIn(
            "<!-- generated by aikito from subagents/formatter.md", rendered_claude_1
        )

        rendered_codex_1 = render_codex_toml(
            "formatter",
            "Runs project-approved formatting and lint-fix operations.",
            {"model": "gpt-5.4-mini", "model_reasoning_effort": "low"},
            "# Formatter\n\nPerform only task.",
        )
        rendered_codex_2 = render_codex_toml(
            "formatter",
            "Runs project-approved formatting and lint-fix operations.",
            {"model": "gpt-5.4-mini", "model_reasoning_effort": "low"},
            "# Formatter\n\nPerform only task.",
        )
        self.assertEqual(rendered_codex_1, rendered_codex_2)
        self.assertIn(
            "# generated by aikito from subagents/formatter.md", rendered_codex_1
        )
        self.assertIn('model = "gpt-5.4-mini"', rendered_codex_1)
        self.assertIn("developer_instructions = '''", rendered_codex_1)

    def test_escaping_and_toml_roundtrip(self) -> None:
        # Test P1 Fix: TOML/YAML escaping and roundtrip parsing
        desc_with_quotes_and_special = (
            'Runs "approved" formatting: lint & fix #1\nsecond line'
        )
        rendered_codex = render_codex_toml(
            "formatter",
            desc_with_quotes_and_special,
            {"model": "gpt-5.4-mini"},
            "# Formatter instructions",
        )
        parsed_toml = tomllib.loads(rendered_codex)
        self.assertEqual(parsed_toml["name"], "formatter")
        self.assertEqual(parsed_toml["description"], desc_with_quotes_and_special)
        self.assertEqual(parsed_toml["model"], "gpt-5.4-mini")
        self.assertEqual(
            parsed_toml["developer_instructions"], "# Formatter instructions\n"
        )

        rendered_claude = render_claude_markdown(
            "formatter",
            desc_with_quotes_and_special,
            {"model": "haiku"},
            "# Instructions",
        )
        self.assertIn(
            'description: "Runs \\"approved\\" formatting: lint & fix #1\\nsecond line"',
            rendered_claude,
        )

    def test_missing_or_typo_subagents_table_fails_and_prevents_prune(self) -> None:
        # Test P1 Fix: Typo in [subagents] table (e.g. [subagent])
        # First create a valid managed file
        sync_subagent_configs(self.aikito_dir, self.home_dir)
        codex_file = self.home_dir / ".codex" / "agents" / "formatter.toml"
        self.assertTrue(codex_file.is_file())

        # Corrupt subagents.toml with typo key [subagent]
        typo_subagents_toml = """
[subagent.formatter]
description = "Runs project-approved formatting."
agents = ["codex"]
"""
        (self.aikito_dir / "subagents.toml").write_text(
            typo_subagents_toml.strip(), encoding="utf-8"
        )

        # Sync with --prune must fail immediately and NOT delete the managed file
        with self.assertRaises(SubagentConfigError) as ctx:
            sync_subagent_configs(self.aikito_dir, self.home_dir, prune=True)

        self.assertIn(
            "'subagents' table in subagents.toml is missing or empty",
            str(ctx.exception),
        )
        self.assertTrue(
            codex_file.is_file(),
            "Existing managed file must not be pruned when config table is missing",
        )

    def test_plan_with_errors_aborts_without_writing_any_files(self) -> None:
        # Test P1 Fix: ERROR in plan prevents all CREATE / UPDATE file modifications
        codex_cfg_dir = self.home_dir / ".codex"
        codex_cfg_dir.mkdir(parents=True)
        (codex_cfg_dir / "config.toml").write_text(
            "[agents]\nenabled = false\n", encoding="utf-8"
        )

        # Attempt sync when Codex has ERROR
        success = sync_subagent_configs(self.aikito_dir, self.home_dir)
        self.assertFalse(success)

        # Neither Codex nor Claude file should be created
        codex_file = self.home_dir / ".codex" / "agents" / "formatter.toml"
        claude_file = self.home_dir / ".claude" / "agents" / "formatter.md"
        self.assertFalse(codex_file.exists())
        self.assertFalse(claude_file.exists())

    def test_codex_renderer_rejects_triple_quotes(self) -> None:
        with self.assertRaises(SubagentConfigError) as ctx:
            render_codex_toml(
                "formatter",
                "Description",
                {},
                "Instruction containing ''' triple quotes",
            )
        self.assertIn("triple single-quotes", str(ctx.exception))

    def test_invalid_platform_field_or_type_fails(self) -> None:
        bad_subagents_toml = """
[subagents.formatter]
description = "Runs project-approved formatting and lint-fix operations."
agents = ["codex"]

[subagents.formatter.codex]
invalid_field = "value"
"""
        (self.aikito_dir / "subagents.toml").write_text(
            bad_subagents_toml.strip(), encoding="utf-8"
        )

        with self.assertRaises(SubagentConfigError) as ctx:
            sync_subagent_configs(self.aikito_dir, self.home_dir)
        self.assertIn("unknown field 'invalid_field'", str(ctx.exception))

    def test_sync_creates_files(self) -> None:
        success = sync_subagent_configs(self.aikito_dir, self.home_dir)
        self.assertTrue(success)

        codex_file = self.home_dir / ".codex" / "agents" / "formatter.toml"
        claude_file = self.home_dir / ".claude" / "agents" / "formatter.md"
        agy_file = (
            self.home_dir / ".gemini" / "config" / "agents" / "formatter" / "agent.md"
        )

        self.assertTrue(codex_file.is_file())
        self.assertTrue(claude_file.is_file())
        self.assertTrue(agy_file.is_file())
        self.assertTrue(has_aikito_marker(codex_file))
        self.assertTrue(has_aikito_marker(claude_file))
        self.assertTrue(has_aikito_marker(agy_file))

        # Check content includes model gpt-5.4-mini
        self.assertIn('model = "gpt-5.4-mini"', codex_file.read_text(encoding="utf-8"))
        self.assertIn('tools: ["run_command"]', agy_file.read_text(encoding="utf-8"))

    def test_sync_empty_subagents_is_successful_noop(self) -> None:
        (self.aikito_dir / "subagents.toml").write_text(
            "[subagents]\n", encoding="utf-8"
        )

        success = sync_subagent_configs(self.aikito_dir, self.home_dir)

        self.assertTrue(success)
        self.assertFalse((self.home_dir / ".codex" / "agents").exists())
        self.assertFalse((self.home_dir / ".claude" / "agents").exists())

    def test_dry_run_and_plan_consistency(self) -> None:
        plan_before, _ = build_plan(self.aikito_dir, self.home_dir)
        create_actions = [p.action for p in plan_before if p.action != "SKIP"]
        self.assertEqual(create_actions, ["CREATE", "CREATE", "CREATE"])

        success = sync_subagent_configs(self.aikito_dir, self.home_dir, dry_run=True)
        self.assertTrue(success)

        codex_file = self.home_dir / ".codex" / "agents" / "formatter.toml"
        self.assertFalse(codex_file.exists())

    def test_unmarked_file_causes_conflict(self) -> None:
        claude_dir = self.home_dir / ".claude" / "agents"
        claude_dir.mkdir(parents=True)
        user_file = claude_dir / "formatter.md"
        user_file.write_text("# My Custom Formatter\nNo marker here.", encoding="utf-8")

        success = sync_subagent_configs(self.aikito_dir, self.home_dir)
        self.assertFalse(success)

        self.assertEqual(
            user_file.read_text(encoding="utf-8"),
            "# My Custom Formatter\nNo marker here.",
        )

        success_force = sync_subagent_configs(
            self.aikito_dir, self.home_dir, force_targets=["claude-code/formatter"]
        )
        self.assertTrue(success_force)
        self.assertTrue(has_aikito_marker(user_file))

    def test_prune_orphans_without_deleting_unrelated(self) -> None:
        sync_subagent_configs(self.aikito_dir, self.home_dir)

        claude_dir = self.home_dir / ".claude" / "agents"
        orphan_file = claude_dir / "old_agent.md"
        orphan_file.write_text(
            "---\nname: old_agent\n---\n<!-- generated by aikito from subagents/old_agent.md - edits will be overwritten -->\n",
            encoding="utf-8",
        )

        unrelated_user_file = claude_dir / "my_custom_tool.md"
        unrelated_user_file.write_text("# User tool", encoding="utf-8")

        plan, _ = build_plan(self.aikito_dir, self.home_dir)
        orphan_items = [p for p in plan if p.action == "ORPHAN"]
        self.assertEqual(len(orphan_items), 1)
        self.assertEqual(orphan_items[0].subagent_name, "old_agent")

        sync_subagent_configs(self.aikito_dir, self.home_dir, prune=False)
        self.assertTrue(orphan_file.exists())
        self.assertTrue(unrelated_user_file.exists())

        sync_subagent_configs(self.aikito_dir, self.home_dir, prune=True)
        self.assertFalse(orphan_file.exists())
        self.assertTrue(unrelated_user_file.exists())

    def test_render_copilot_markdown(self) -> None:
        opts = {
            "tools": ["read", "search", "edit"],
            "user-invocable": True,
            "disable-model-invocation": False,
        }
        rendered = render_copilot_markdown(
            "formatter",
            "Runs project-approved formatting.",
            opts,
            "Perform formatting task.",
        )
        self.assertIn('name: "formatter"', rendered)
        self.assertIn('description: "Runs project-approved formatting."', rendered)
        self.assertIn('tools: ["read", "search", "edit"]', rendered)
        self.assertIn("user-invocable: true", rendered)
        self.assertIn("disable-model-invocation: false", rendered)
        self.assertIn("<!-- generated by aikito from subagents/formatter.md", rendered)
        self.assertIn("Perform formatting task.", rendered)


if __name__ == "__main__":
    unittest.main()
