"""Adapter parity and reusable definition-driven platform validation."""

import json
from pathlib import Path

import pytest

from aikito.agents import load_agent_definitions
from aikito.subagent import (
    AgentSubagentConfig,
    SubagentDefinition,
    build_subagent_plan,
    get_target_subagent_path,
    render_subagent,
)
from aikito.subagent_adapters import SubagentConfigError, get_subagent_adapter
from aikito.subagent_validation import validate_platform_opts
from layout_helpers import write_agents


GOLDEN = json.loads(
    (Path(__file__).parent / "fixtures/subagent-adapter-parity.json").read_text()
)


@pytest.mark.parametrize("format", GOLDEN)
def test_rendering_preserves_existing_bytes(format):
    sample = GOLDEN[format]
    definition = SubagentDefinition(
        "review",
        "Review changes",
        ["example"],
        {"example": sample["options"]},
        "Review carefully.\n\nKeep 用户 context.",
    )
    config = AgentSubagentConfig("example", "Example", Path("/target"), format)
    assert render_subagent(definition, config) == sample["rendered"]


def test_custom_platform_reuses_adapter(tmp_path):
    ws, home = tmp_path / "ws", tmp_path / "home"
    ws.mkdir()
    home.mkdir()
    write_agents(
        ws,
        """[agents.example]
[agents.example.detect]
paths = [".example"]
[agents.example.subagents]
config_path = ".example/agents"
config_format = "claude_markdown"
""",
    )
    (home / ".example").mkdir()
    (ws / "subagents/review.md").write_text("""---
description: "Review changes"
agents: ["example"]
example: {"model": "example", "effort": "high"}
---
Review carefully.
""")
    plan = build_subagent_plan(ws, home)
    assert plan.operations[0].action == "CREATE"
    assert 'model: "example"' in plan.file_plans[0].final_content
    agents = load_agent_definitions(ws, home)
    with pytest.raises(SubagentConfigError, match="unknown field"):
        validate_platform_opts("example", "review", {"maxTokens": 1}, agents=agents)
    with pytest.raises(SubagentConfigError, match="no defined"):
        validate_platform_opts("undefined", "review", {}, agents=agents)


@pytest.mark.parametrize(
    "format,suffix",
    [
        ("agy_markdown", "review/agent.md"),
        ("copilot_markdown", "review.agent.md"),
        ("codex_toml", "review.toml"),
    ],
)
def test_paths_and_managed_orphans(tmp_path, format, suffix):
    config = AgentSubagentConfig("example", "Example", tmp_path, format)
    path = get_target_subagent_path(config, "review")
    assert path == tmp_path / suffix
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("# generated by aikito from subagents/review.md\n")
    assert get_subagent_adapter(format).list_managed(tmp_path) == {"review": path}


def test_unknown_adapter_fails_closed():
    with pytest.raises(SubagentConfigError, match="Unsupported"):
        get_subagent_adapter("unknown")


def test_reused_codex_adapter_checks_disabled_capability(tmp_path):
    ws, home = tmp_path / "ws", tmp_path / "home"
    write_agents(
        ws,
        """[agents.example]
[agents.example.detect]
paths = [".example"]
[agents.example.subagents]
config_path = ".example/agents"
config_format = "codex_toml"
""",
    )
    (home / ".example").mkdir(parents=True)
    (home / ".example/config.toml").write_text("[agents]\nenabled = false\n")
    plan = build_subagent_plan(ws, home, allow_empty=True)
    assert not plan.can_apply
    assert any(
        op.action == "ERROR" and "disabled" in op.reason for op in plan.operations
    )


def test_reused_adapter_respects_optional_prerequisite(tmp_path):
    ws, home = tmp_path / "ws", tmp_path / "home"
    write_agents(
        ws,
        """[agents.example]
[agents.example.detect]
paths = [".example"]
[agents.example.subagents]
config_path = ".example/agents"
config_format = "pi_markdown"
requires_path = ".example/extension.ts"
""",
    )
    (home / ".example").mkdir(parents=True)
    plan = build_subagent_plan(ws, home, allow_empty=True)
    assert any(
        op.action == "SKIP" and "Optional subagent capability" in op.reason
        for op in plan.operations
    )


def test_shared_patch_freezes_content_and_protects_stale_plan(tmp_path):
    from aikito.subagent import execute_subagent_plan

    ws, home = tmp_path / "ws", tmp_path / "home"
    write_agents(
        ws,
        """[agents.example]
[agents.example.detect]
paths = [".example"]
[agents.example.subagents]
config_path = ".example/cordis.patch.yml"
config_format = "dsh_cordis_subagent"
""",
    )
    (home / ".example").mkdir(parents=True)
    path = home / ".example/cordis.patch.yml"
    path.write_text("# Existing shared configuration\n")
    (ws / "subagents/review.md").write_text(
        '---\ndescription: "Review"\nagents: ["example"]\n---\nReview.\n'
    )
    plan = build_subagent_plan(ws, home)
    frozen = plan.file_plans[0].final_content
    assert "aikito-subagent-review" in frozen
    path.write_text("# External edit\n")
    result = execute_subagent_plan(plan, home)
    assert not result.success and "stale" in result.error_message.lower()
    assert path.read_text() == "# External edit\n"
    plan = build_subagent_plan(ws, home)
    result = execute_subagent_plan(plan, home)
    assert result.success
    assert path.read_text() == plan.file_plans[0].final_content
    backups = list((home / ".local/state/aikito/backups").rglob("*"))
    assert any(
        item.is_file() and item.read_text() == "# External edit\n" for item in backups
    )
