"""Native subagent semantics; Core owns conflict protection and file transactions."""

from __future__ import annotations

import json
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from collections.abc import Callable, Mapping, Sequence
from typing import Any, Literal

from .config_runtime import ConfigOperation

MARKER_PREFIX = "generated by aikito from subagents/"


class SubagentConfigError(RuntimeError):
    """Raised when subagent configuration or target file operations fail."""


def get_marker_text(subagent_name: str) -> str:
    return f"generated by aikito from subagents/{subagent_name}.md - edits will be overwritten"


def has_aikito_marker_text(text: str) -> bool:
    return MARKER_PREFIX in text


def has_aikito_marker(file_path: Path) -> bool:
    if not file_path.is_file():
        return False
    try:
        with file_path.open("r", encoding="utf-8", errors="replace") as f:
            for _ in range(10):
                line = f.readline()
                if not line:
                    break
                if MARKER_PREFIX in line:
                    return True
    except Exception:
        return False
    return False


def render_copilot_markdown(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = ["---"]

    opts = dict(platform_opts)
    if "name" not in opts:
        opts["name"] = name
    opts["description"] = description

    for k in sorted(opts.keys()):
        val = opts[k]
        if isinstance(val, bool):
            lines.append(f"{k}: {'true' if val else 'false'}")
        elif isinstance(val, list):
            encoded_list = json.dumps(val, ensure_ascii=False)
            lines.append(f"{k}: {encoded_list}")
        else:
            lines.append(f"{k}: {json.dumps(val, ensure_ascii=False)}")

    lines.append("---")
    lines.append(f"<!-- {marker} -->")
    lines.append("")
    lines.append(instructions)
    lines.append("")
    return "\n".join(lines)


def render_claude_markdown(
    name: str, description: str, platform_opts: dict[str, str], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = [
        "---",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
    ]
    for k in sorted(platform_opts.keys()):
        lines.append(f"{k}: {json.dumps(platform_opts[k], ensure_ascii=False)}")
    lines.append("---")
    lines.append(f"<!-- {marker} -->")
    lines.append("")
    lines.append(instructions)
    lines.append("")
    return "\n".join(lines)


def render_opencode_markdown(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = [
        "---",
        f"description: {json.dumps(description, ensure_ascii=False)}",
        'mode: "subagent"',
    ]
    for k in sorted(platform_opts.keys()):
        lines.append(f"{k}: {json.dumps(platform_opts[k], ensure_ascii=False)}")
    lines.append("---")
    lines.append(f"<!-- {marker} -->")
    lines.append("")
    lines.append(instructions)
    lines.append("")
    return "\n".join(lines)


def render_grok_markdown(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = [
        "---",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
    ]
    for key in sorted(platform_opts):
        value = platform_opts[key]
        if isinstance(value, bool):
            lines.append(f"{key}: {'true' if value else 'false'}")
        else:
            lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    lines.extend(["---", f"<!-- {marker} -->", "", instructions, ""])
    return "\n".join(lines)


def render_pi_markdown(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = [
        "---",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
    ]
    if "model" in platform_opts:
        lines.append(f"model: {json.dumps(platform_opts['model'], ensure_ascii=False)}")
    if "tools" in platform_opts:
        lines.append(f"tools: {json.dumps(platform_opts['tools'], ensure_ascii=False)}")
    lines.extend(["---", f"<!-- {marker} -->", "", instructions, ""])
    return "\n".join(lines)


def render_codex_toml(
    name: str, description: str, platform_opts: dict[str, str], instructions: str
) -> str:
    if "'''" in instructions:
        raise SubagentConfigError(
            f"Instructions for subagent '{name}' contain triple single-quotes ('''), which is invalid for codex_toml literal string."
        )

    marker = get_marker_text(name)
    lines = [
        f"# {marker}",
        f"name = {json.dumps(name, ensure_ascii=False)}",
        f"description = {json.dumps(description, ensure_ascii=False)}",
    ]
    for k in sorted(platform_opts.keys()):
        lines.append(f"{k} = {json.dumps(platform_opts[k], ensure_ascii=False)}")

    lines.append("developer_instructions = '''")
    lines.append(instructions)
    lines.append("'''")
    lines.append("")
    rendered = "\n".join(lines)

    # Verify round-trip parsing for TOML
    try:
        tomllib.loads(rendered)
    except Exception as exc:
        raise SubagentConfigError(
            f"Rendered Codex TOML for '{name}' is invalid TOML: {exc}"
        )

    return rendered


def render_agy_markdown(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    lines = [
        "---",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
    ]
    for k in sorted(platform_opts.keys()):
        lines.append(f"{k}: {json.dumps(platform_opts[k], ensure_ascii=False)}")
    lines.append("---")
    lines.append(f"<!-- {marker} -->")
    lines.append("")
    lines.append(instructions)
    lines.append("")
    return "\n".join(lines)


def _split_cordis_patch_items(text: str) -> list[tuple[int, int, str]]:
    """Split YAML list into (start_idx, end_idx, item_text) tuples for top-level list items."""
    item_starts: list[int] = []
    for match in re.finditer(r"(?m)^-[ \t]+", text):
        item_starts.append(match.start())

    if not item_starts:
        stripped = text.lstrip()
        if stripped.startswith("-"):
            item_starts.append(text.find("-"))
        else:
            return []

    items: list[tuple[int, int, str]] = []
    for i, start in enumerate(item_starts):
        end = item_starts[i + 1] if i + 1 < len(item_starts) else len(text)
        items.append((start, end, text[start:end]))
    return items


def _parse_cordis_subagent_plugin_item(item_text: str) -> dict[str, Any]:
    """Parse key fields from a single Cordis plugin item in YAML."""
    result: dict[str, Any] = {}
    lines = item_text.splitlines()
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" in stripped:
            k, v = stripped.split(":", 1)
            k = k.strip().lstrip("- ").strip()
            v = v.strip().strip("'\"")
            if k in ("id", "name", "toolName", "provider"):
                result[k] = v
    return result


def get_dsh_cordis_subagent_item(text: str, name: str) -> str | None:
    """Find the raw YAML item block for aikito-subagent-<name> if present."""
    if not text.strip():
        return None
    items = _split_cordis_patch_items(text)
    for _, _, item_text in items:
        info = _parse_cordis_subagent_plugin_item(item_text)
        plugin_id = info.get("id", "")
        plugin_name = info.get("name", "")
        tool_name = info.get("toolName", "")
        if plugin_id == f"aikito-subagent-{name}" or (
            plugin_name == "@deepseek-ai/dsh-tool-subagent" and tool_name == name
        ):
            return item_text
    return None


def get_all_dsh_cordis_subagents(text: str) -> list[str]:
    """Find all subagent names managed by Aikito in cordis.patch.yml."""
    if not text.strip():
        return []
    names = []
    items = _split_cordis_patch_items(text)
    for _, _, item_text in items:
        if not has_aikito_marker_text(item_text):
            continue
        info = _parse_cordis_subagent_plugin_item(item_text)
        plugin_id = info.get("id", "")
        if plugin_id.startswith("aikito-subagent-"):
            names.append(plugin_id.removeprefix("aikito-subagent-"))
        elif (
            info.get("name") == "@deepseek-ai/dsh-tool-subagent" and "toolName" in info
        ):
            names.append(info["toolName"])
    return names


def update_dsh_cordis_subagent(text: str, name: str, rendered_block: str) -> str:
    """Update or append an @deepseek-ai/dsh-tool-subagent plugin item in cordis.patch.yml."""
    if not text.strip():
        return rendered_block + "\n"

    items = _split_cordis_patch_items(text)
    for start, end, item_text in items:
        info = _parse_cordis_subagent_plugin_item(item_text)
        plugin_id = info.get("id", "")
        plugin_name = info.get("name", "")
        tool_name = info.get("toolName", "")
        if plugin_id == f"aikito-subagent-{name}" or (
            plugin_name == "@deepseek-ai/dsh-tool-subagent" and tool_name == name
        ):
            trailing = "" if item_text.endswith("\n") else "\n"
            return text[:start] + rendered_block + trailing + text[end:]

    separator = (
        "\n" if text.endswith("\n\n") else ("\n\n" if text.endswith("\n") else "\n\n")
    )
    return text.rstrip() + separator + rendered_block + "\n"


def remove_dsh_cordis_subagent(text: str, name: str) -> str:
    """Remove an @deepseek-ai/dsh-tool-subagent plugin item from cordis.patch.yml."""
    if not text.strip():
        return ""

    items = _split_cordis_patch_items(text)
    for start, end, item_text in items:
        info = _parse_cordis_subagent_plugin_item(item_text)
        plugin_id = info.get("id", "")
        plugin_name = info.get("name", "")
        tool_name = info.get("toolName", "")
        if plugin_id == f"aikito-subagent-{name}" or (
            plugin_name == "@deepseek-ai/dsh-tool-subagent" and tool_name == name
        ):
            new_text = (text[:start] + text[end:]).strip()
            return (new_text + "\n") if new_text else ""
    return text


def render_dsh_cordis_subagent(
    name: str, description: str, platform_opts: dict[str, Any], instructions: str
) -> str:
    marker = get_marker_text(name)
    provider = str(platform_opts.get("provider", "spawn"))
    lines = [
        f"- id: aikito-subagent-{name}",
        f"  # {marker}",
        "  name: '@deepseek-ai/dsh-tool-subagent'",
        "  config:",
        f"    provider: {provider}",
        f"    toolName: {name}",
    ]
    if "model" in platform_opts or "maxTokens" in platform_opts:
        lines.append("    agentOptions:")
        if "model" in platform_opts:
            lines.append(
                f"      model: {json.dumps(platform_opts['model'], ensure_ascii=False)}"
            )
        if "maxTokens" in platform_opts:
            lines.append(f"      maxTokens: {platform_opts['maxTokens']}")
    if "backgroundMode" in platform_opts:
        lines.append(f"    backgroundMode: {platform_opts['backgroundMode']}")
    if "tools" in platform_opts and isinstance(platform_opts["tools"], list):
        lines.append("    toolFilter:")
        lines.append("      allow:")
        for t in platform_opts["tools"]:
            lines.append(f"        - {t}")

    indented_instructions = "\n".join(
        ("      " + line) if line else "" for line in instructions.splitlines()
    )
    lines.append("    persona: |-")
    lines.append(indented_instructions)
    return "\n".join(lines)


def check_codex_enabled(home: Path) -> tuple[bool, str]:
    return _check_codex_config(home / ".codex" / "config.toml")


def _check_codex_config(codex_config: Path) -> tuple[bool, str]:
    if not codex_config.is_file():
        return True, ""
    try:
        with codex_config.open("rb") as f:
            data = tomllib.load(f)
        agents_sec = data.get("agents")
        if isinstance(agents_sec, dict) and agents_sec.get("enabled") is False:
            return (
                False,
                "Codex agents capability is explicitly disabled in ~/.codex/config.toml ([agents] enabled = false)",
            )
    except Exception:
        pass
    return True, ""


@dataclass(frozen=True)
class SubagentAdapter:
    render: Callable[[str, str, dict[str, Any], str], str]
    extension: str = ".md"
    layout: Literal["per_file", "shared_patch"] = "per_file"
    allowed_fields: frozenset[str] = frozenset()
    option_types: Mapping[str, str] = field(default_factory=dict)
    target_path: Callable[[Path, str], Path] | None = None
    managed_entries: Callable[[Path], dict[str, Path]] | None = None
    read_item: Callable[[str, str], str | None] | None = None
    merge: Callable[[str, Sequence[ConfigOperation]], str] | None = None
    availability_check: Callable[[Path], tuple[bool, str]] | None = None

    def validate_options(
        self, agent_name: str, subagent_name: str, options: dict[str, Any]
    ) -> dict[str, Any]:
        if not isinstance(options, dict):
            raise SubagentConfigError(
                f"Subagent '{subagent_name}' platform '{agent_name}' must be a table"
            )
        validated = {}
        for key, value in options.items():
            if key not in self.allowed_fields:
                raise SubagentConfigError(
                    f"Subagent '{subagent_name}' contains unknown field '{key}' for platform '{agent_name}'. Allowed: {sorted(self.allowed_fields)}"
                )
            kind = self.option_types.get(key, "string")
            if kind == "tools" and isinstance(value, str):
                value = [value]
            valid = {
                "string": lambda: isinstance(value, str) and bool(value.strip()),
                "tools": lambda: (
                    isinstance(value, list)
                    and all(isinstance(item, str) and item.strip() for item in value)
                ),
                "strings": lambda: (
                    isinstance(value, list)
                    and all(isinstance(item, str) and item.strip() for item in value)
                ),
                "boolean": lambda: isinstance(value, bool),
                "table_or_string": lambda: isinstance(value, (str, dict)),
                "positive_integer": lambda: (
                    isinstance(value, int) and not isinstance(value, bool) and value > 0
                ),
                "background": lambda: (
                    isinstance(value, str) and value in ("one-shot", "continuable")
                ),
            }[kind]()
            if not valid:
                raise SubagentConfigError(
                    f"Subagent '{subagent_name}' field '{key}' for platform '{agent_name}' has invalid value ({kind})"
                )
            validated[key] = value
        return validated

    def resolve_target_path(self, root: Path, name: str) -> Path:
        if self.target_path:
            return self.target_path(root, name)
        return root / f"{name}{self.extension}"

    def list_managed(self, root: Path) -> dict[str, Path]:
        if self.managed_entries:
            return self.managed_entries(root)
        if not root.is_dir():
            return {}
        return {
            path.name[: -len(self.extension)]: path
            for path in sorted(root.iterdir())
            if path.is_file()
            and path.name.endswith(self.extension)
            and has_aikito_marker(path)
        }


def _agy_managed(root: Path) -> dict[str, Path]:
    if not root.is_dir():
        return {}
    return {
        path.name: path / "agent.md"
        for path in sorted(root.iterdir())
        if path.is_dir() and has_aikito_marker(path / "agent.md")
    }


def _cordis_managed(root: Path) -> dict[str, Path]:
    text = root.read_text(encoding="utf-8") if root.is_file() else ""
    return dict.fromkeys(get_all_dsh_cordis_subagents(text), root)


def _merge_cordis(text: str, operations: Sequence[ConfigOperation]) -> str:
    for op in operations:
        if not op.is_authorized:
            continue
        if op.action in ("CREATE", "UPDATE"):
            text = update_dsh_cordis_subagent(
                text, op.target.logical_identity, op.rendered_payload or ""
            )
        elif op.action in ("REMOVE", "ORPHAN"):
            text = remove_dsh_cordis_subagent(text, op.target.logical_identity)
    return text


def _codex_available(root: Path) -> tuple[bool, str]:
    return _check_codex_config(root.parent / "config.toml")


SUBAGENT_ADAPTERS: dict[str, SubagentAdapter] = {
    "codex_toml": SubagentAdapter(
        render_codex_toml,
        extension=".toml",
        allowed_fields=frozenset({"model", "model_reasoning_effort"}),
        availability_check=_codex_available,
    ),
    "claude_markdown": SubagentAdapter(
        render_claude_markdown, allowed_fields=frozenset({"model", "effort"})
    ),
    "agy_markdown": SubagentAdapter(
        render_agy_markdown,
        allowed_fields=frozenset({"tools", "model"}),
        option_types={"tools": "tools"},
        target_path=lambda root, name: root / name / "agent.md",
        managed_entries=_agy_managed,
    ),
    "copilot_markdown": SubagentAdapter(
        render_copilot_markdown,
        extension=".agent.md",
        allowed_fields=frozenset(
            {
                "name",
                "description",
                "model",
                "tools",
                "target",
                "disable-model-invocation",
                "user-invocable",
            }
        ),
        option_types={
            "tools": "tools",
            "disable-model-invocation": "boolean",
            "user-invocable": "boolean",
        },
    ),
    "opencode_markdown": SubagentAdapter(
        render_opencode_markdown, allowed_fields=frozenset({"model"})
    ),
    "dsh_cordis_subagent": SubagentAdapter(
        render_dsh_cordis_subagent,
        extension="",
        layout="shared_patch",
        allowed_fields=frozenset(
            {"provider", "tools", "model", "maxTokens", "backgroundMode"}
        ),
        option_types={
            "tools": "tools",
            "maxTokens": "positive_integer",
            "backgroundMode": "background",
        },
        target_path=lambda root, name: root,
        managed_entries=_cordis_managed,
        read_item=get_dsh_cordis_subagent_item,
        merge=_merge_cordis,
    ),
    "grok_markdown": SubagentAdapter(
        render_grok_markdown,
        allowed_fields=frozenset(
            {
                "model",
                "reasoning_effort",
                "prompt_mode",
                "permission_mode",
                "agents_md",
                "tools",
                "skills",
                "mcpInheritance",
            }
        ),
        option_types={
            "agents_md": "boolean",
            "tools": "tools",
            "skills": "strings",
            "mcpInheritance": "table_or_string",
        },
    ),
    "pi_markdown": SubagentAdapter(
        render_pi_markdown,
        allowed_fields=frozenset({"model", "tools"}),
        option_types={"tools": "tools"},
    ),
}


def get_subagent_adapter(config_format: str) -> SubagentAdapter:
    try:
        return SUBAGENT_ADAPTERS[config_format]
    except KeyError as exc:
        raise SubagentConfigError(
            f"Unsupported subagent config_format '{config_format}'"
        ) from exc
